package nif;
/* CVS $Id: $ */

import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from E:/Master Project/jena schemagen/its-rdf.rdf 
 * @author Auto-generated by schemagen on 30 Jun 2015 13:54 
 */
public class ITSRDF_SchemaGen {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.w3.org/2005/11/its/rdf#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Property allowedCharacters = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#allowedCharacters" );
    
    public static final Property dir = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#dir" );
    
    public static final Property domains = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#domains" );
    
    public static final Property externalResourceRef = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#externalResourceRef" );
    
    public static final Property hasLocQualityIssue = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#hasLocQualityIssue" );
    
    public static final Property hasProvRecord = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#hasProvRecord" );
    
    public static final Property id = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#id" );
    
    public static final Property lineBreakType = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#lineBreakType" );
    
    public static final Property locNote = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#locNote" );
    
    public static final Property locNoteRef = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#locNoteRef" );
    
    public static final Property locNoteType = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#locNoteType" );
    
    public static final Property locQualityIssueComment = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#locQualityIssueComment" );
    
    public static final Property locQualityIssueEnabled = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#locQualityIssueEnabled" );
    
    public static final Property locQualityIssueProfileRef = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#locQualityIssueProfileRef" );
    
    public static final Property locQualityIssueSeverity = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#locQualityIssueSeverity" );
    
    public static final Property locQualityIssueType = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#locQualityIssueType" );
    
    public static final Property locQualityRatingProfileRef = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#locQualityRatingProfileRef" );
    
    public static final Property locQualityRatingScore = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#locQualityRatingScore" );
    
    public static final Property locQualityRatingScoreThreshold = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#locQualityRatingScoreThreshold" );
    
    public static final Property locQualityRatingVote = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#locQualityRatingVote" );
    
    public static final Property locQualityRatingVoteThreshold = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#locQualityRatingVoteThreshold" );
    
    public static final Property localeFilterList = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#localeFilterList" );
    
    public static final Property localeFilterType = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#localeFilterType" );
    
    public static final Property mtConfidence = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#mtConfidence" );
    
    public static final Property mtConfidenceAnnotatorsRef = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#mtConfidenceAnnotatorsRef" );
    
    public static final Property org = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#org" );
    
    public static final Property orgRef = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#orgRef" );
    
    public static final Property person = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#person" );
    
    public static final Property personRef = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#personRef" );
    
    public static final Property provRef = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#provRef" );
    
    public static final Property revOrg = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#revOrg" );
    
    public static final Property revOrgRef = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#revOrgRef" );
    
    public static final Property revPerson = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#revPerson" );
    
    public static final Property revPersonRef = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#revPersonRef" );
    
    public static final Property revTool = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#revTool" );
    
    public static final Property revToolRef = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#revToolRef" );
    
    public static final Property space = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#space" );
    
    public static final Property storageEncoding = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#storageEncoding" );
    
    public static final Property storageSize = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#storageSize" );
    
    public static final Property taAnnotatorsRef = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#taAnnotatorsRef" );
    
    public static final Property taConfidence = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#taConfidence" );
    
    public static final Property taIdent = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#taIdent" );
    
    public static final Property taIdentRef = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#taIdentRef" );
    
    public static final Property taSource = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#taSource" );
    
    public static final Property target = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#target" );
    
    public static final Property term = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#term" );
    
    public static final Property termAnnotatorsRef = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#termAnnotatorsRef" );
    
    public static final Property termConfidence = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#termConfidence" );
    
    public static final Property termInfoRef = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#termInfoRef" );
    
    public static final Property tool = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#tool" );
    
    public static final Property toolRef = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#toolRef" );
    
    public static final Property translate = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#translate" );
    
    public static final Property withinText = m_model.createProperty( "http://www.w3.org/2005/11/its/rdf#withinText" );
    
    public static final Resource LocQualityIssue = m_model.createResource( "http://www.w3.org/2005/11/its/rdf#LocQualityIssue" );
    
    public static final Resource ProvRecord = m_model.createResource( "http://www.w3.org/2005/11/its/rdf#ProvRecord" );
    
}
